// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

/*
Package service_product is a generated protocol buffer package.

It is generated from these files:
	product.proto

It has these top-level messages:
	ProductInfo
	ResponseProduct
*/
package service_product

import (
	fmt "fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProductInfo struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Sku  string `protobuf:"bytes,2,opt,name=sku" json:"sku,omitempty"`
}

func (m *ProductInfo) Reset()                    { *m = ProductInfo{} }
func (m *ProductInfo) String() string            { return proto.CompactTextString(m) }
func (*ProductInfo) ProtoMessage()               {}
func (*ProductInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProductInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductInfo) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

type ResponseProduct struct {
	ProductId int64   `protobuf:"varint,1,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	Price     float32 `protobuf:"fixed32,2,opt,name=price" json:"price,omitempty"`
}

func (m *ResponseProduct) Reset()                    { *m = ResponseProduct{} }
func (m *ResponseProduct) String() string            { return proto.CompactTextString(m) }
func (*ResponseProduct) ProtoMessage()               {}
func (*ResponseProduct) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseProduct) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *ResponseProduct) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func init() {
	proto.RegisterType((*ProductInfo)(nil), "service.product.ProductInfo")
	proto.RegisterType((*ResponseProduct)(nil), "service.product.ResponseProduct")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x28, 0xca, 0x4f,
	0x29, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb,
	0x4c, 0x4e, 0xd5, 0x83, 0x0a, 0x2b, 0x19, 0x73, 0x71, 0x07, 0x40, 0x98, 0x9e, 0x79, 0x69, 0xf9,
	0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60,
	0xb6, 0x90, 0x00, 0x17, 0x73, 0x71, 0x76, 0xa9, 0x04, 0x13, 0x58, 0x08, 0xc4, 0x54, 0x72, 0xe3,
	0xe2, 0x0f, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x85, 0x6a, 0x16, 0x92, 0xe5, 0xe2, 0x82,
	0x1a, 0x19, 0x9f, 0x99, 0x02, 0xd6, 0xce, 0x1c, 0xc4, 0x09, 0x15, 0xf1, 0x4c, 0x11, 0x12, 0xe1,
	0x62, 0x2d, 0x28, 0xca, 0x4c, 0x4e, 0x05, 0x9b, 0xc2, 0x14, 0x04, 0xe1, 0x18, 0x45, 0x72, 0xb1,
	0xc3, 0xf4, 0xfb, 0x71, 0x71, 0x39, 0xa6, 0xa4, 0xc0, 0x78, 0x32, 0x7a, 0x68, 0xee, 0xd4, 0x43,
	0x72, 0xa4, 0x94, 0x02, 0x86, 0x2c, 0x9a, 0x6b, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0xfe, 0x35, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x98, 0x19, 0xf8, 0x1e, 0x00, 0x01, 0x00, 0x00,
}
